class_descriptions = {
    0: {"name": "Abimanyu", "description": "Abimanyu adalah putra Arjuna dan Subhadra, serta keponakan Kresna. Sejak dalam kandungan, ia telah mendengar ilmu strategi perang dari ayahnya. Dalam perang Bharatayudha, Abimanyu menunjukkan keberanian luar biasa saat mencoba menembus formasi Cakravyuha yang rumit. Namun, karena kurangnya pengetahuan untuk keluar dari formasi tersebut, ia terperangkap dan akhirnya gugur sebagai pahlawan muda yang dihormati."},
    1: {"name": "Anoman", "description": "Anoman, atau Hanuman dalam epos Ramayana, adalah kera putih sakti yang setia kepada Rama. Ia memiliki kemampuan terbang, kekuatan luar biasa, dan kebijaksanaan tinggi. Anoman berperan penting dalam pencarian Sinta, istri Rama, yang diculik oleh Rahwana. Dengan keberaniannya, Anoman berhasil menemukan Sinta di Alengka dan membantu Rama dalam pertempuran melawan Rahwana untuk membebaskannya."},
    2: {"name": "Arjuna", "description": "Arjuna adalah salah satu dari lima Pandawa dalam epos Mahabharata. Ia dikenal sebagai pemanah ulung dan memiliki sifat bijaksana serta tampan. Arjuna sering melakukan tapa dan belajar dari berbagai resi untuk meningkatkan kemampuannya. Dalam perang Bharatayudha, Arjuna memainkan peran kunci dalam kemenangan Pandawa atas Kurawa, terutama dengan membunuh Karna, salah satu ksatria terkuat di pihak lawan. "},
    3: {"name": "Bima", "description": "Bima, atau Werkudara, adalah Pandawa kedua yang dikenal dengan kekuatan fisik luar biasa dan sifatnya yang tegas. Ia memiliki senjata andalan berupa gada bernama Rujakpala. Meskipun tampak keras, Bima memiliki hati yang lembut dan sangat setia kepada saudara-saudaranya. Dalam perang Bharatayudha, Bima berhasil membunuh Duryodana, pemimpin Kurawa, dengan menghancurkan pahanya, sesuai sumpahnya untuk membalas perlakuan buruk terhadap Drupadi."},
    4: {"name": "Cakil", "description": "Cakil adalah tokoh raksasa dalam dunia pewayangan yang sering menjadi antagonis. Ia biasanya muncul sebagai penghalang bagi para ksatria dalam mencapai tujuan mereka. Dengan wajah menyeramkan dan sifat licik, Cakil selalu berusaha mengalahkan lawannya dengan tipu daya. Namun, dalam setiap pertunjukan, Cakil selalu kalah, melambangkan kemenangan kebaikan atas kejahatan."},
    5: {"name": "Dusarsana", "description": "Dursasana adalah adik Duryodana dan salah satu dari seratus Kurawa. Ia dikenal karena kesetiaannya kepada Duryodana dan sering terlibat dalam perbuatan licik. Salah satu tindakan paling kejamnya adalah saat ia mencoba menelanjangi Drupadi di depan umum setelah Pandawa kalah dalam permainan dadu. Tindakannya ini menimbulkan kemarahan Bima, yang bersumpah untuk membalas dendam dengan membunuh Dursasana dan meminum darahnya, sebuah sumpah yang akhirnya ia penuhi dalam perang Bharatayudha."},
    6: {"name": "Duryudana", "description": "Duryodana adalah pemimpin Kurawa dan antagonis utama dalam Mahabharata. Ia memiliki ambisi besar untuk menguasai kerajaan Hastinapura dan tidak segan-segan menggunakan cara licik untuk mencapai tujuannya. Duryodana menolak memberikan bagian kerajaan yang sah kepada Pandawa, yang memicu perang Bharatayudha. Meskipun memiliki banyak ksatria hebat di pihaknya, Duryodana akhirnya tewas di tangan Bima, menandai berakhirnya dominasi Kurawa."},
    7: {"name": "Gatotkaca", "description": "Gatotkaca adalah putra Bima dan Arimbi, seorang raksasa wanita yang kemudian menjadi cantik. Sejak lahir, Gatotkaca menunjukkan tanda-tanda kesaktian, terutama setelah mendapatkan anugerah tubuh sekuat baja dan kemampuan terbang tanpa sayap. Dalam perang Bharatayudha, Gatotkaca menjadi andalan Pandawa untuk menghadapi musuh-musuh tangguh. Ia akhirnya gugur sebagai pahlawan saat melawan Karna, yang menggunakan senjata sakti Indrastra untuk mengalahkannya."},
    8: {"name": "Karna", "description": "Karna adalah ksatria hebat yang sebenarnya saudara tertua Pandawa, namun tidak diketahui identitasnya hingga menjelang akhir hidupnya. Ia dibesarkan oleh keluarga kusir dan selalu merasa terpinggirkan karena statusnya. Karna memiliki keahlian memanah yang luar biasa dan setia kepada Duryodana, yang pertama kali mengakui kemampuannya dan memberinya status sebagai raja. Dalam perang Bharatayudha, meskipun mengetahui kebenaran tentang asal-usulnya, Karna tetap berperang di pihak Kurawa dan akhirnya tewas di tangan Arjuna."},
    9: {"name": "Kresna", "description": "Kresna adalah inkarnasi dewa Wisnu yang berperan sebagai penasihat Pandawa. Ia dikenal bijaksana, cerdas, dan memiliki pandangan jauh ke depan. Kresna memainkan peran penting dalam strategi perang Bharatayudha dan sering memberikan nasihat moral kepada Arjuna, termasuk ajaran-ajaran yang terkandung dalam Bhagavad Gita. Setelah perang, Kresna kembali ke kerajaannya dan akhirnya meninggalkan dunia fana sesuai dengan takdirnya."},
    10: {"name": "Patih Sabrang", "description": "Patih Sabrang adalah seorang patih dalam cerita pewayangan yang sering digambarkan sebagai tokoh setia kepada rajanya. Meskipun tidak sepopuler tokoh-tokoh lain, Patih Sabrang sering muncul dalam lakon-lakon tertentu sebagai pejabat kerajaan yang berusaha menjalankan tugasnya dengan baik."},
    11: {"name": "Petruk", "description": "Petruk adalah salah satu Punakawan dalam dunia pewayangan, dikenal karena sifatnya yang humoris dan cerdas. Ia sering muncul sebagai penghibur dalam cerita wayang, tetapi di balik kelucuannya, Petruk memiliki kebijaksanaan yang mendalam. Ia sering memberikan nasihat berharga kepada para ksatria, terutama Pandawa, melalui candaan dan sindiran yang mengandung makna filosofis. Dalam beberapa versi cerita, Petruk juga digambarkan memiliki latar belakang istimewa sebagai anak seorang raja yang memilih hidup sederhana. Ia sering berperan sebagai pengingat bahwa kekuasaan dan kebijaksanaan sejati tidak selalu datang dari mereka yang berada di singgasana, melainkan dari mereka yang memahami makna hidup dengan baik."},
    12: {"name": "Puntadewa", "description": "Puntadewa, atau Yudistira, adalah sulung dari lima Pandawa yang dikenal akan kesabarannya yang luar biasa. Ia dijuluki sebagai raja yang paling adil dan tidak pernah berbohong sepanjang hidupnya. Dalam Mahabharata, Puntadewa menjadi pemimpin Pandawa yang selalu mengutamakan perdamaian, bahkan ketika saudara-saudaranya lebih memilih perang sebagai solusi konflik dengan Kurawa. Selama perang Bharatayudha, meskipun ia seorang pemimpin, Puntadewa jarang bertarung secara langsung dan lebih banyak berperan sebagai pengatur strategi. Setelah perang berakhir, ia dinobatkan sebagai raja Hastinapura dan memimpin dengan kebijaksanaan hingga akhirnya memilih meninggalkan kerajaan untuk mencari pencerahan spiritual."},
    13: {"name": "Semar", "description": "Semar adalah pemimpin Punakawan dan sering disebut sebagai titisan dewa dalam bentuk manusia sederhana. Ia memiliki wajah tua, tubuh gemuk, tetapi penuh dengan kebijaksanaan. Semar adalah penasihat utama Pandawa, memberikan petuah yang penuh filosofi dengan cara yang mudah dipahami, baik oleh raja maupun rakyat jelata. Dalam banyak lakon wayang, Semar sering digambarkan sebagai sosok yang mampu menenangkan konflik dengan humor dan petuah bijaknya. Meskipun tampak sebagai seorang pelayan atau rakyat biasa, Semar sebenarnya memiliki kesaktian luar biasa yang hanya digunakan dalam keadaan darurat untuk menegakkan kebenaran dan keadilan."},
    14: {"name": "Sengkuni", "description": "Sengkuni adalah tokoh antagonis dalam Mahabharata yang dikenal licik dan penuh tipu daya. Ia adalah paman dari para Kurawa dan menjadi penasihat utama Duryodana. Dengan kepandaiannya dalam berbicara, Sengkuni sering memprovokasi Duryodana untuk bertindak jahat terhadap Pandawa, termasuk dalam peristiwa permainan dadu yang membuat Pandawa kehilangan kerajaan mereka. Meskipun cerdik, Sengkuni akhirnya mengalami nasib tragis dalam perang Bharatayudha. Semua rencananya untuk menghancurkan Pandawa berakhir dengan kegagalan, dan ia sendiri tewas di tangan Bima. Kematian Sengkuni melambangkan bahwa kejahatan dan tipu daya tidak akan pernah menang melawan kebenaran."},
}

